### ISSUE TITLE
[gotalk.js] Uncaught ReferenceError: s is not defined

### ISSUE THREAD

**Issue by oskca** [rsms/gotalk#10]
when using gotalk.js in browser side, Sock.notify and Sock.stopSendingHeartbeats all have the error message:`Uncaught ReferenceError: s is not defined`. When I'm looking through the code I found [this](https://github.com/rsms/gotalk/blob/master/js/gotalk/index.js#L192) in `gotalk/index.js`:

``` javascript
Sock.prototype.stopSendingHeartbeats = function() {
  clearTimeout(s._sendHeartbeatsTimer);
};
```

and this for [Sock.bufferNotify](https://github.com/rsms/gotalk/blob/master/js/gotalk/index.js#L392)

```
Sock.prototype.bufferNotify = function(name, buf) {
  s.sendMsg(protocol.MsgTypeNotification, null, name, 0, buf);
}
```

is this right?

**Comment by rsms** [comment]
Fixed in c77cf4e923ee2cfe8f26f24ef3c34baf052dc02e
