### ISSUE TITLE
Add an example with encrypted connections.

### ISSUE THREAD

**Issue by mark-kubacki** [rsms/gotalk#3]
Please add an example for establishing encrypted connections. A quite important feature nowadays.

You are welcome to include my script if you use TLS:
https://gist.github.com/wmark/c758ce1c2b8222afd69d

**Comment by elimisteve** [comment]
+1 for crypto

**Comment by rsms** [comment]
Yup. We need an example of using TLS.
I'm currently working on [v1](https://github.com/rsms/gotalk/tree/v1) and we should add the example to this branch as master is currently the protocol v0 "draft" which I won't touch.

**Comment by djcas9** [comment]
Any update on this.

**Comment by djcas9** [comment]
@rsms is this something you plan to add? If not let me know - i'll fork and get it done with weekend. I'm using your project currently in one of mine [https://github.com/mephux/envdb](https://github.com/mephux/envdb) and its a big show stopped atm. If you have api/design requests please let me know.

**Comment by nkev** [comment]
@rsms Is this project abandoned? You don't seem to be responding to issues or the pull request.

**Comment by rsms** [comment]
Note that for HTTP, gotalk operates over whatever transport the server uses, so if you run gotalk in a https server with go, data is encrypted.

So, no tests or examples needed for encrypted HTTP. What could be useful is an example of plain TCP connections with TLS.

**Comment by rsms** [comment]
There's now a new TLS example here https://github.com/rsms/gotalk/tree/master/examples/tls and v1.1.0 adds some convenience functions for making it easier to use TLS like `ListenTLS` and `ConnectTLS`.
