### ISSUE TITLE
gotalk/js: exit status 3221225725

### ISSUE THREAD

**Issue by pavel-main** [rsms/gotalk#6]
This happens on windows amd64, because of this file
https://github.com/rsms/gotalk/blob/master/js/gotalk.js.go

Is there any way to avoid large amount of string concatenations? According to @bradfitz it's the main problem, similar bug https://code.google.com/p/go/issues/detail?id=8240#c2

**Comment by ai-pavel** [comment]
I've prepared PR #7, it works with back-quotes
